version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.coil-kt:coil
    versions:
    - 1.2.0
  - dependency-name: com.google.dagger:hilt-android-compiler
    versions:
    - 2.31.2-alpha
    - 2.32-alpha
    - 2.34-beta
  - dependency-name: com.google.dagger:hilt-android
    versions:
    - 2.31.2-alpha
    - 2.32-alpha
    - 2.34-beta
  - dependency-name: com.google.dagger:hilt-android-gradle-plugin
    versions:
    - 2.31.2-alpha
    - 2.32-alpha
    - 2.34-beta
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 7.0.0-alpha05
    - 7.0.0-alpha06
    - 7.0.0-alpha07
    - 7.0.0-alpha08
    - 7.0.0-alpha09
    - 7.0.0-alpha10
    - 7.0.0-alpha11
    - 7.0.0-alpha12
    - 7.0.0-alpha13
  - dependency-name: androidx.lifecycle:lifecycle-runtime-ktx
    versions:
    - 2.3.0
    - 2.3.1
  - dependency-name: androidx.lifecycle:lifecycle-viewmodel-ktx
    versions:
    - 2.3.0
    - 2.3.1
  - dependency-name: androidx.lifecycle:lifecycle-livedata-ktx
    versions:
    - 2.3.0
    - 2.3.1
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: androidx.navigation:navigation-safe-args-gradle-plugin
    versions:
    - 2.3.3
    - 2.3.4
  - dependency-name: androidx.datastore:datastore-preferences
    versions:
    - 1.0.0-alpha07
    - 1.0.0-alpha08
  - dependency-name: androidx.navigation:navigation-ui-ktx
    versions:
    - 2.3.3
    - 2.3.4
  - dependency-name: androidx.navigation:navigation-fragment-ktx
    versions:
    - 2.3.3
    - 2.3.4
  - dependency-name: org.jlleitschuh.gradle.ktlint
    versions:
    - 10.0.0
  - dependency-name: junit:junit
    versions:
    - 4.13.2
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
  - dependency-name: androidx.work:work-runtime-ktx
    versions:
    - 2.5.0
  - dependency-name: androidx.work:work-runtime
    versions:
    - 2.5.0
  - dependency-name: androidx.hilt:hilt-compiler
    versions:
    - 1.0.0-alpha03
  - dependency-name: androidx.hilt:hilt-work
    versions:
    - 1.0.0-alpha03
  - dependency-name: androidx.hilt:hilt-lifecycle-viewmodel
    versions:
    - 1.0.0-alpha03
